### PR TITLE
New ProtoData: one run, multiple dirs

### PR DESCRIPTION
**Pull request by dmdashenkov**
This PR updates the ProtoData version on top of which the lib is built.

### CODE REVIEW

**Comment by dmdashenkov** [comment]
@armiol, PTAL.

**Review by armiol — CHANGES_REQUESTED** [review]
@dmdashenkov 
Please revert the changes made to `buildSrc`.

In `validation`, it's actually a newer version of files. It's just that due to the conflicts in third-party libs (Error Prone in particular), the `config` contents aren't updated yet.

**Comment by dmdashenkov** [comment]
@armiol, PTAL.

**Review by armiol — APPROVED** [review]
LGTM.

**Pull request merged**
